### ISSUE TITLE
Trying unsucessfully to authenticate SignalR against AMS

### ISSUE THREAD

**Issue by apollyonbob** [Azure/azure-mobile-services#478]
I am having a heck of a time trying to figure out how one is supposed to have AMS authentication with SignalR while using a JavaScript client. I don't even know if this is the right forum for this question, but it relates to AMS so I'm hoping someone here has some ideas.

I downloaded the JavaScript client for Azure Mobile Services, I've got Signal R on AMS - that's all hooked up and ready to go. I've got the authentication setup. I can actually call .login("microsoftaccount") on the AMS JS client and go through that process and get back a token and id.

What I don't know is how to connect the two.

I tried just calling $.connection.hub.Start() - it gives me 401. I tried putting the token in the query string, again it gives me 401. Am I supposed to be calling a login function via SignalR somehow? Passing the token to SignalR? If so, how?

Or do I need to make some custom thing? If so, what?

Thanks!

**Comment by mdonstad** [comment]
Is this going to be fixed? Can we use the suggestion of passing x-zumo-auth in qs now?

**Comment by steelcityrkp** [comment]
I'm also curious about this.  Has this been resolved in regards to authenticating through the query string?

I have been trying, unsuccessfully so far, to connect a Web-Based Client (administrative dashboard) to my SignalR which is on a ZUMO Service that is interacting successfully with the Mobile Clients (android app).

I have oriented everything around this, but cannot get a working WebSocket connection between the Web Client and ZUMO Service; I had one aspect working once, where some in-browser dialog popper up, and I would enter the App key; however, I still wasn't getting the actual Service User and able to derive the user information.

Any guidance or perspective would be highly appreciated.

Primarily, however, though is this QS based authentiation being fixed?  It seems like this would solve everything for me?  [If not, any suggestions on work around?]

**Comment by WiteCastle** [comment]
I'm having a really hard time with the JS Client as well. My call to start the connection comes back with a 200 but it still calls the fail function. I tried the above solution by passing x-zumo-application as headers for ajax calls and changing the connection to longPolling but still no luck. Is there anything special I need to be aware of for the server side of the SignalR hub? Is there a in depth walkthrough of how to get the JS client to work with AMS SignalR?

    connection.start( { transport : 'longPolling' })
        .done(function () { console.log('Now connected, connection ID=' + connection.id); })
        .fail(function () { console.log('Could not connect'); });
    var headers = {};
    headers['x-zumo-application'] = 'app-password';
    $.ajaxSetup({ headers: headers });

**Comment by boblautenbach** [comment]
There is a fix for this.  On your AMS site or App, go to the configuration tab, scroll down to Cross-orgin resource sharing (CORS).  Enter * , save and restart the service.  Or you can enter the know domains that will access it (more secure).  This is the JS I have working with it.  FYI..you need jquery-signalr-2.1.0.  2.2.0 is not supported by azure server yet.  Also, this only works if you set to this in AMS
webApiconfig SignalRExtensionConfig.Initialize();
            options.SetRealtimeAuthorization(AuthorizationLevel.Anonymous);

I am still playing around with getting it to work with "Application"

    <script>
        console.log('running');
       
        var connection = $.hubConnection('https://yourazurename.azure-mobile.net');
        var hubProxy = connection.createHubProxy('thehubyouwanttoconnectto');

        hubProxy.on('methodthehubwillfirebacktoclient', function (message) {
            console.log('The Response....');
            console.log(message);
        });

        connection.start({ transport: 'auto' })
        .done(function (connection) { 
            console.log('Now connected, connection ID=' + connection.id);

            hubProxy.invoke('hubmethodtoinvoke', 'param1').done(function () {
                console.log('Invocation of hubmethodtoinvoke succeeded');
            }).fail(function (error) {
                console.log('Invocation of hubmethodtoinvoke failed. Error: ' + error);
            });
        })
        .fail(function (error) {
           console.log('Could not connect' + error);
        });
    </script>
